import {configurationName} from './config.js';
import type {Connection} from './runtime.js';
function mapping(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Expected a YAML mapping');return value as Record<string,unknown>;}
function fields(data:Record<string,unknown>,allowed:string[]){const extra=Object.keys(data).filter(k=>!allowed.includes(k));if(extra.length)throw new Error('Unsupported connection fields: '+extra.join(', '));}
export function connections(value:unknown):Record<string,Connection>{
 const result:Record<string,Connection>=Object.create(null);
 for(const [key,input] of Object.entries(mapping(value))){configurationName(key);const item=mapping(input);if(item.description!==undefined&&typeof item.description!=='string')throw new Error('Connection description must be text');const description=typeof item.description==='string'?item.description.trim():undefined;if(item.type!=='mcp')throw new Error('Connection type must be mcp');
  if(item.url!==undefined){fields(item,['type','url','auth','env_var','description']);if(typeof item.url!=='string'||!['native','none','bearer_env'].includes(String(item.auth)))throw new Error('Only HTTPS MCP with auth=native, none, or bearer_env is supported');const url=new URL(item.url);if(url.protocol!=='https:'||!url.hostname||url.username||url.password||url.search||url.hash||/\s/.test(item.url))throw new Error('Use an HTTPS endpoint without credentials or query parameters');if(item.auth==='bearer_env'){if(typeof item.env_var!=='string'||!/^[A-Za-z_][A-Za-z0-9_]*$/.test(item.env_var))throw new Error('MCP bearer_env requires env_var to name an environment variable');result[key]={type:'mcp',description,url:item.url,auth:'bearer_env',env_var:item.env_var};}else{if(item.env_var!==undefined)throw new Error('MCP env_var requires auth: bearer_env');result[key]={type:'mcp',description,url:item.url,auth:item.auth as 'native'|'none'};}}
  else{fields(item,['type','command','args','env','env_vars','description']);if(typeof item.command!=='string'||!item.command.trim()||/[\r\n\0]/.test(item.command))throw new Error('Local MCP requires a command executable');const args=item.args??[],env=mapping(item.env??{}),envVars=item.env_vars??[],envName=(v:unknown)=>typeof v==='string'&&/^[A-Za-z_][A-Za-z0-9_]*$/.test(v);if(!Array.isArray(args)||args.some(v=>typeof v!=='string'||v.includes('\0')))throw new Error('MCP args must be a list of strings');if(Object.entries(env).some(([k,v])=>!envName(k)||typeof v!=='string'||v.includes('\0')))throw new Error('MCP env must map environment names to strings');if(!Array.isArray(envVars)||envVars.some(v=>!envName(v))||new Set(envVars).size!==envVars.length)throw new Error('MCP env_vars must be unique environment names');if(envVars.some(v=>Object.hasOwn(env,v)))throw new Error('MCP env and env_vars cannot overlap');result[key]={type:'mcp',description,command:item.command,args,env:env as Record<string,string>,env_vars:envVars};}
 }
 return result;
}

